### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by sachaarbonel** [brickpop/flutter-rust-ffi#1]
Thank you for solving this ! I've been working hard on this too and I don't think I would have found the trick of adding a dummy function to my swift library. That's a weird behavior, don't you think there is something we can do ? Maybe the Dart team can have a look at this.

For the android part I prefer to use cargo-gradle because it rebuilds when my Rust code changes you should definitely check it [out](https://github.com/sachaarbonel/jisho.rs).

**Comment by rodydavis** [comment]
https://github.com/rodydavis/flutter_ffi_webassembly for wasm support!

**Comment by brickpop** [comment]
> Thank you for solving this ! I've been working hard on this too and I don't think I would have found the trick of adding a dummy function to my swift library. That's a weird behavior, don't you think there is something we can do ? Maybe the Dart team can have a look at this.

Yes, that's a trick I found thanks to a comment stating that XCode will not link a library unless it detects some usage. I don't think there's much to be done from the Dart team perspective. 

In relation to gradle, you could always try to invoke `make android` on the rust folder, but it's nice to hear about Cargo gradle. I'll have a look at it, thanks.

**Comment by brickpop** [comment]
> https://github.com/rodydavis/flutter_ffi_webassembly for wasm support!

There are many similar folders to look at. Not sure which is the right one :)

`flutter_wasmer` looks interesting for desktop

**Comment by rodydavis** [comment]
@brickpop yes! Its all my current experiments with Flutter, Dart and Rust

**Comment by rodydavis** [comment]
@brickpop also this is my package for WASM from rust https://pub.dev/packages/flutter_wasm_interop

**Comment by brickpop** [comment]
@rodydavis I'll be glad to see it running on mobile+desktop :)
