### ISSUE TITLE
Compile on Windows Machine

### ISSUE THREAD

**Issue by canewsin** [brickpop/flutter-rust-ffi#2]
make script not working on Windows.

**Comment by brickpop** [comment]
The makefile is mainly a Unix build tool, and it fits quite well to develop for Android (Linux) and iOS (Darwin).

You may want to have a try with [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) or use [Cygwin](https://cygwin.com/install.html). However, this would only allow to compile APK's fow Android. To compile for iOS you need to run macOS.

**Comment by TENX-S** [comment]
> make script not working on Windows.

@canewsin [This](https://github.com/TENX-S/flutter-rust-ffi-windows) project might be helpful.
