### ISSUE TITLE
How to read `Bundle Identifier` for IOS and `package` for Android in `rust flutter`?

### ISSUE THREAD

**Issue by Aaron009** [brickpop/flutter-rust-ffi#20]
As the title?

I plan to use rust to take some safety measures to prevent "cracking".

Thank you for the template, it is really useful!

**Comment by brickpop** [comment]
I guess you'd have to look if some Rust crates provide wrappers around the Android NDK and/or Apple's UIKit. The intent of this repo is to offload heavy/complex mobile computations to Rust, doing the business logic in Rust is not the main goal of this template.

If you find useful hints, feel free to submit a PR to improve the example :)
