### ISSUE TITLE
Web support?

### ISSUE THREAD

**Issue by bootstraponline** [brickpop/flutter-rust-ffi#4]
Is it possible to call Rust from Flutter Web using wasm?

**Comment by rodydavis** [comment]
It is possible 😉 I was able to do it with a wrapper using wasmer in rust 💪🏻

**Comment by dvc94ch** [comment]
Can you make a PR for this repo? That would be great, as flutter-rs will probably turn out to be a dead end for now. This seems to be a much better approach.

**Comment by brickpop** [comment]
This boilerplate is focused towards loading native libraries on mobile flutter apps. Adding desktop support should not be difficult, but Flutter Web is a different creature. 

As of now, I think there is no official support to handle wasm libraries from flutter web. The repo could be easily adapted to also generate wasm files, but the integration on a web would need to be done from the main HTML body, hacky ad dirty.
