### ISSUE TITLE
How to force Xcode to link unused

### ISSUE THREAD

**Issue by bugeats** [brickpop/flutter-rust-ffi#8]
From the README:

> NOTE: By default, XCode will skip bundling the libexample.a library if it detects that it is not being used. To force its inclusion, add a dummy method in SwiftMylibPlugin.swift that uses at least one of the native functions.

Do you know how to force Xcode to always bundle static libs? In my case, I'm not using a Flutter plugin, and just trying to use a single universal .a file.

**Comment by brickpop** [comment]
Not sure about your use case, I can mostly talk about the Flutter plugin scenario.

One option is to try to add the `.a` file on XCode within the compilation target.

The other option is to use Cocoa Pods to do the dependency management for you:
https://github.com/brickpop/flutter-rust-ffi/blob/master/ios/mylib.podspec

You will still need the  `.h` file with the relevant symbols and an explicit invocation from swift/objc.
