### ISSUE TITLE
Could you write a similar article on how to use Golang and Flutter together for desktop?

### ISSUE THREAD

**Issue by ganeshrvel** [brickpop/flutter-rust-ffi#9]
I have been trying to setup a project to use Flutter and Golang together for macOS.

I followed two of your articles https://medium.com/stack-me-up/meet-the-coolest-tech-marriage-flutter-go-369cf11367c9 and https://medium.com/flutter-community/using-ffi-on-flutter-plugins-to-run-native-rust-code-d64c0f14f9c2 but unfortunately I could not get the setup happen.

I got lost at macOS bundle security and dylib linking using xcode.

How do I expose the golang native functions into flutter app for desktop? 
Could you write a similar article on how to use Golang and Flutter together for desktop or any pointers will be appreciated.

**Comment by brickpop** [comment]
Hi ganeshrvel,

I'm glad you followed the other article. Unfortunately, I'm not sure at which point you get stuck.

> I got lost at macOS bundle security and dylib linking using xcode.

What step do you mean by bundle security? Go mobile will generate a `.framework` file for iOS, which contains the binary libraries and all the glue code already working for you. 

You need to either (1) drag it into your XCode project (manual setup) or (2) tell Cocoa Pods to add `MyLibrary.framework` for you within the plugin. Linking and bundling will happen when you compile the final flutter app.

Exposing the raw native go functions as we do in Rust is not really an option. I have been exploring what `gomobile`and `gobind` do under the hood, and it look like there is no way around the extra Go glue code, and Java/Swift glue code as well. 

I have tried compiling with `GOOS` and `GOARCH` but this won't simply do the trick. At the moment, go mobile, seems the way to go. If I find a better way, I'll follow up with the article and probably prepare an equivalent repo.
